C3D
ericknavarro/ProyectoJisonJS pull request #1
Opened 2020-02-25 02:45 UTC by Puac235

Generación de C3D utilizando jison.

2020-02-28 00:08 UTC, rjanixz commented
@Puac235 podrías indicarme cual es el propósito de este PR?

Veo que has cambiado la gramática completamente.

2020-03-02 14:56 UTC, Puac235 commented
Hace unos días el ing. Navarro dijo que si podíamos, aplicaríamos la generación de C3D a un lenguaje (python o js) utilizando como base el proyecto. Yo lo realicé en este repositorio con jison, y cuando le comenté esto al ingeniero me dijo que realizará un pull request para que el lo revisara.

2020-03-02 15:23 UTC, rjanixz requested changes
@Puac235 te comento que la idea es agregar funcionalidades al proyecto existente, es decir, tomar como base la gramática existente y extender su funcionalidad. En este caso, según veo, cambiaste toda la gramática sobreescribiendo las funcionalidades existentes, lo cual afecta el [tutorial](https://ericknavarro.io/2019/07/21/17-Mi-primer-proyecto-utilizando-Jison-Linux/) y los pull request de tus demás compañeros.

Te recomiendo que adaptes tu propuesta a la funcionalidad existente, cualquier duda, quedo a la oden.

Saludos.

2020-03-03 02:50 UTC, ericknavarro commented
Estimado @Puac235 , aprecio mucho tu iniciativa, sin embargo el propósito de tu PR se desvía demasiado de el objetivo del proyecto en este repositorio, por otro lado me gustaría que quedara esta otra versión en tus repositorios, para consultarla en caso decidamos hacer algún tutorial específico sobre generación de código intermedio, como sabrás el objetivo de este proyecto es realizar un intérprete sencillo, los cambios que propones estarían más orientados a generar un compilador, por otro lado me gustaría que @rjanixz te diera su opinión general sobre tu proyecto y de estar correcto que pueda contar como una contribución incluso si no se llegó a hacer merge.

Saludos cordiales.

2020-03-03 02:50 UTC, closed without merging

2020-03-03 04:28 UTC, rjanixz commented
@Puac235 buen trabajo, tu pr genera correctamente el código 3 direcciones, por esto tomaremos como vaído la exoneración del corto. Mandame un correo con tus datos: carnet, nombre, usuario de github, sección, número de issue, y número de pull request para control de tu nota.

2020-03-04 04:59 UTC, Puac235 commented
201700342, José Francisco Puac Ixcamparic, Puac235, B+